export default {
    Splash: "Splash",
    Login: "Login",
    PhoneSignup: "PhoneSignup",
    OTPConfirmation: "OTPConfirmation",
    Chat: "Chat",
    MessagesList: "MessagesList",
    PhoneContacts: "PhoneContacts",
    SettingsScreen: "SettingsScreen",
    Messaging: "Messaging",
    BasicDetails: "BasicDetails",
    Address: "Address",
    Account: "Account",
    SetPin: "SetPin",
    Wallet: "Wallet",
}